name: Build and push godaddy webhook image
on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: snowdrop/cert-manager-webhook-godaddy
          addLatest: true
          enableBuildKit: true
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USER }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}