name: Build and push godaddy webhook image
on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      #- name: Install go 1.16
      #  uses: actions/setup-go@v2
      #  with:
      #    go-version: 1.16

      - name: Login to Quay.io Hub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USER }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build the container image
        run: |
          VERSION=$(git rev-parse --short HEAD 2>/dev/null)
          docker buildx build --platform linux/amd64,linux/arm64 --load --tag cert-manager-webhook-godaddy:${VERSION} -f Dockerfile .

          TAG_ID=$(docker images -q cert-manager-webhook-godaddy:${VERSION})
          echo "Tagging the images using as tag id: ${TAG_ID} and version: ${VERSION}"
          
          docker tag ${TAG_ID} quay.io/snowdrop/cert-manager-webhook-godaddy:${VERSION}
          docker tag ${TAG_ID} quay.io/snowdrop/cert-manager-webhook-godaddy:latest

          docker push quay.io/snowdrop/cert-manager-webhook-godaddy:${VERSION}
          docker push quay.io/snowdrop/cert-manager-webhook-godaddy:latest